import {
  calculateEconomics,
  type Deal,
  type ReleaseEvent,
  type SourceStatus,
} from './domain.ts';

const deal = (
  value: Omit<Deal, 'economics'> & {
    economics: Parameters<typeof calculateEconomics>[0];
  },
): Deal => ({ ...value, economics: calculateEconomics(value.economics) });

export const deals: Deal[] = [
  deal({
    id: 'pe-etb-pair',
    title: '2x Prismatic Evolutions ETB — ophalen of verzenden',
    canonicalProduct: 'Prismatic Evolutions Elite Trainer Box × 2',
    game: 'Pokémon',
    set: 'Prismatic Evolutions',
    productType: 'Elite trainer box',
    source: 'Marktplaats',
    dataMode: 'demo',
    sourceListingUrl: 'https://demo.invalid/listing/pe-etb-pair',
    sourceListingId: 'demo-pe-etb-pair',
    sourceMarketplace: 'fixture-market',
    lastVerifiedAt: '2026-09-04T06:49:00.000Z',
    availabilityStatus: 'available',
    detectedAt: '2026-09-04T06:38:00.000Z',
    location: 'Utrecht, NL',
    language: 'English',
    condition: 'Sealed · light shelf wear',
    quantity: 2,
    seller: 'Cardzolder88',
    sellerScore: 96,
    listingAge: '11 min',
    detectedMinutesAgo: 11,
    matchConfidence: 97,
    confidenceGrade: 'A',
    liquidity: 'Very liquid',
    soldCount30d: 43,
    activeListings: 18,
    medianDaysToSell: 8,
    instantScore: 92,
    holdScore: 68,
    riskScore: 18,
    status: 'Hot Hunt',
    exitChannel: 'Cardmarket',
    priceEvidence:
      '18 fictional demonstration transactions · 3 fixture sources',
    risks: ['Packaging condition requires photo check'],
    catalysts: ['Below current EU sold range', 'High recent sell-through'],
    tags: ['Local option', 'Rechecked', 'Fast exit'],
    tint: 'emerald',
    tracked: true,
    economics: {
      itemPrice: 118,
      inboundShipping: 6.95,
      buyerFees: 1.5,
      paymentFees: 0,
      importCosts: 0,
      travelCost: 0,
      acquisitionLabor: 0,
      expectedSalePrice: 195,
      sellerFees: 19,
      exitPaymentFees: 2.5,
      outboundShipping: 7.25,
      packaging: 1.8,
      expectedReturnLoss: 3.5,
      sellingLabor: 4,
      liquidityHaircut: 2,
      estimatedHours: 1.1,
      expectedHoldingDays: 18,
      requiredProfit: 25,
    },
  }),
  deal({
    id: 'destined-rivals-box',
    title: 'Destined Rivals Booster Box sealed EN — quick sale',
    canonicalProduct: 'Destined Rivals Booster Box',
    game: 'Pokémon',
    set: 'Destined Rivals',
    productType: 'Booster box',
    source: 'eBay',
    dataMode: 'demo',
    sourceListingUrl: 'https://demo.invalid/listing/destined-rivals-box',
    sourceListingId: 'demo-destined-rivals-box',
    sourceMarketplace: 'fixture-market',
    lastVerifiedAt: '2026-09-04T06:23:00.000Z',
    availabilityStatus: 'available',
    detectedAt: '2026-09-04T05:46:00.000Z',
    location: 'Köln, DE',
    language: 'English',
    condition: 'Factory sealed',
    quantity: 1,
    seller: 'rhein-cards',
    sellerScore: 99,
    listingAge: '37 min',
    detectedMinutesAgo: 37,
    matchConfidence: 94,
    confidenceGrade: 'A',
    liquidity: 'Liquid',
    soldCount30d: 28,
    activeListings: 34,
    medianDaysToSell: 14,
    instantScore: 84,
    holdScore: 74,
    riskScore: 24,
    status: 'Strong Value',
    exitChannel: 'eBay NL',
    priceEvidence: '12 fictional demonstration transactions · 4 fixtures',
    risks: ['German seller; verify seal photos'],
    catalysts: ['Price cut detected', 'Stable sales volume'],
    tags: ['Cross-border', 'Price drop'],
    tint: 'blue',
    tracked: false,
    economics: {
      itemPrice: 112,
      inboundShipping: 7.5,
      buyerFees: 0,
      paymentFees: 1.25,
      importCosts: 0,
      travelCost: 0,
      acquisitionLabor: 0,
      expectedSalePrice: 166,
      sellerFees: 13.8,
      exitPaymentFees: 1.2,
      outboundShipping: 6.95,
      packaging: 1.5,
      expectedReturnLoss: 2.5,
      sellingLabor: 3,
      liquidityHaircut: 2,
      estimatedHours: 0.8,
      expectedHoldingDays: 35,
      requiredProfit: 25,
    },
  }),
  deal({
    id: 'riftbound-display',
    title: 'Riftbound Origins booster display — sealed case fresh',
    canonicalProduct: 'Riftbound Origins Booster Display',
    game: 'Riftbound',
    set: 'Origins',
    productType: 'Display',
    source: 'Card Corner EU',
    dataMode: 'demo',
    sourceListingUrl: 'https://demo.invalid/listing/riftbound-display',
    sourceListingId: 'demo-riftbound-display',
    sourceMarketplace: 'fixture-market',
    lastVerifiedAt: '2026-09-04T04:31:00.000Z',
    availabilityStatus: 'available',
    detectedAt: '2026-09-04T04:29:00.000Z',
    location: 'Antwerpen, BE',
    language: 'English',
    condition: 'Factory sealed',
    quantity: 1,
    seller: 'Card Corner EU',
    sellerScore: 97,
    listingAge: '2 h',
    detectedMinutesAgo: 121,
    matchConfidence: 96,
    confidenceGrade: 'B',
    liquidity: 'Moderate',
    soldCount30d: 9,
    activeListings: 41,
    medianDaysToSell: 31,
    instantScore: 41,
    holdScore: 72,
    riskScore: 33,
    status: 'Rejected after costs',
    exitChannel: 'Cardmarket',
    priceEvidence: '6 sold comps · asking prices shown separately',
    risks: ['Thin sold history', 'Current discount disappears after fees'],
    catalysts: ['Tournament season in six weeks'],
    tags: ['Fee trap', 'Shadow only'],
    tint: 'violet',
    tracked: true,
    economics: {
      itemPrice: 139,
      inboundShipping: 8,
      buyerFees: 0,
      paymentFees: 2,
      importCosts: 0,
      travelCost: 0,
      acquisitionLabor: 0,
      expectedSalePrice: 169,
      sellerFees: 12,
      exitPaymentFees: 0,
      outboundShipping: 6,
      packaging: 2,
      expectedReturnLoss: 3,
      sellingLabor: 2,
      liquidityHaircut: 0,
      estimatedHours: 0.8,
      expectedHoldingDays: 46,
      requiredProfit: 25,
    },
  }),
  deal({
    id: 'empty-box-trap',
    title: 'Pokemon 151 display box ONLY leeg / empty — read!',
    canonicalProduct:
      'Scarlet & Violet—151 Booster Bundle display (empty packaging)',
    game: 'Pokémon',
    set: 'Scarlet & Violet—151',
    productType: 'Empty packaging',
    source: 'Marktplaats',
    dataMode: 'demo',
    sourceListingUrl: 'https://demo.invalid/listing/empty-box-trap',
    sourceListingId: 'demo-empty-box-trap',
    sourceMarketplace: 'fixture-market',
    lastVerifiedAt: '2026-09-04T06:42:00.000Z',
    availabilityStatus: 'available',
    detectedAt: '2026-09-04T06:24:00.000Z',
    location: 'Eindhoven, NL',
    language: 'Dutch',
    condition: 'Used · empty',
    quantity: 1,
    seller: 'poke_stuff_nl',
    sellerScore: 89,
    listingAge: '18 min',
    detectedMinutesAgo: 18,
    matchConfidence: 98,
    confidenceGrade: 'B',
    liquidity: 'Illiquid',
    soldCount30d: 1,
    activeListings: 12,
    medianDaysToSell: 74,
    instantScore: 8,
    holdScore: 2,
    riskScore: 96,
    status: 'Likely Trap',
    exitChannel: 'None',
    priceEvidence: 'Title explicitly says empty; excluded from product comps',
    risks: ['Empty packaging', 'Headline price is not a sealed product'],
    catalysts: [],
    tags: ['Misleading title', 'Excluded'],
    tint: 'crimson',
    tracked: false,
    economics: {
      itemPrice: 22,
      inboundShipping: 6.95,
      buyerFees: 0,
      paymentFees: 0,
      importCosts: 0,
      travelCost: 0,
      acquisitionLabor: 0,
      expectedSalePrice: 8,
      sellerFees: 1,
      exitPaymentFees: 0,
      outboundShipping: 4.25,
      packaging: 1,
      expectedReturnLoss: 0,
      sellingLabor: 5,
      liquidityHaircut: 1,
      estimatedHours: 0.8,
      expectedHoldingDays: 120,
      requiredProfit: 25,
    },
  }),
  deal({
    id: 'binder-lot',
    title: 'Oude pokemon map + kaarten, holos? alles in één keer',
    canonicalProduct: 'Mixed Pokémon binder lot · 84 visible items',
    game: 'Pokémon',
    set: 'Mixed eras',
    productType: 'Collection lot',
    source: 'Marktplaats',
    dataMode: 'demo',
    sourceListingUrl: 'https://demo.invalid/listing/binder-lot',
    sourceListingId: 'demo-binder-lot',
    sourceMarketplace: 'fixture-market',
    lastVerifiedAt: '2026-09-04T02:41:00.000Z',
    availabilityStatus: 'available',
    detectedAt: '2026-09-04T02:37:00.000Z',
    location: 'Breda, NL · pickup',
    language: 'Mixed',
    condition: 'Unknown from photos',
    quantity: 84,
    seller: 'zoldervondst',
    sellerScore: 82,
    listingAge: '4 h',
    detectedMinutesAgo: 248,
    matchConfidence: 58,
    confidenceGrade: 'D',
    liquidity: 'Unknown',
    soldCount30d: null,
    activeListings: null,
    medianDaysToSell: null,
    instantScore: 52,
    holdScore: 29,
    riskScore: 72,
    status: 'Speculative',
    exitChannel: 'Individual Cardmarket listings + bulk residual',
    priceEvidence: '31/84 items identified · manual review required',
    risks: [
      '53 unknown items valued at zero',
      'Condition and authenticity uncertain',
    ],
    catalysts: ['Three visible vintage holos merit inspection'],
    tags: ['Ugly listing', 'Lot Lab', 'Manual review'],
    tint: 'amber',
    tracked: false,
    economics: {
      itemPrice: 140,
      inboundShipping: 0,
      buyerFees: 0,
      paymentFees: 0,
      importCosts: 0,
      travelCost: 18,
      acquisitionLabor: 25,
      expectedSalePrice: 292,
      sellerFees: 24,
      exitPaymentFees: 4,
      outboundShipping: 22,
      packaging: 12,
      expectedReturnLoss: 14,
      sellingLabor: 56,
      liquidityHaircut: 35,
      estimatedHours: 6.5,
      expectedHoldingDays: 150,
      requiredProfit: 100,
    },
  }),
];

export const releases: ReleaseEvent[] = [
  {
    id: 'riftbound-spiritforged',
    game: 'Riftbound',
    name: 'Spiritforged',
    product: 'Booster Display',
    releaseDate: '2026-09-18',
    daysAway: 14,
    status: 'Preorder open',
    official: true,
    msrp: 139.99,
    preorderRange: '€129–€159',
    retailerCount: 7,
    demand: 'High',
    watched: true,
    source: 'Riot Games',
  },
  {
    id: 'pokemon-autumn-set',
    game: 'Pokémon',
    name: 'Mega Evolution—Azure Storm',
    product: 'Elite Trainer Box',
    releaseDate: '2026-10-09',
    daysAway: 35,
    status: 'Officially announced',
    official: true,
    msrp: 54.99,
    preorderRange: '€49–€64',
    retailerCount: 11,
    demand: 'Medium',
    watched: false,
    source: 'Pokémon official news',
  },
  {
    id: 'riftbound-regional',
    game: 'Riftbound',
    name: 'Regional restock wave',
    product: 'Origins Booster Display',
    releaseDate: '2026-09-11',
    daysAway: 7,
    status: 'Community report',
    official: false,
    msrp: 139.99,
    preorderRange: '€139–€174',
    retailerCount: 3,
    demand: 'Early',
    watched: true,
    source: 'Unconfirmed retailer reports',
  },
];

export const sources: SourceStatus[] = [
  {
    id: 'fixture-market',
    name: 'Isolated Demo Marketplace',
    mode: 'Fixture',
    health: 'Healthy',
    lastScan: 'On demand',
    nextScan: 'Manual demo run',
    records: 2,
    access: 'Bundled fictional records',
    note: 'No external requests; demo records never enter production storage.',
  },
  {
    id: 'ebay',
    name: 'eBay Browse (live)',
    mode: 'Live',
    health: 'Credentials required',
    lastScan: 'Never',
    nextScan: 'After setup',
    records: 0,
    access: 'Official API',
    note: 'Active asks only; sold evidence remains separate.',
  },
  {
    id: 'marktplaats',
    name: 'Marktplaats',
    mode: 'Disabled',
    health: 'Credentials required',
    lastScan: 'Never',
    nextScan: 'Manual search available',
    records: 0,
    access: 'Authorized API',
    note: 'No scraping fallback. Saved-search links remain available.',
  },
  {
    id: 'cardmarket',
    name: 'Cardmarket Public Data',
    mode: 'Disabled',
    health: 'Credentials required',
    lastScan: 'Never',
    nextScan: 'After setup',
    records: 0,
    access: 'Public catalogue + price guide',
    note: 'Daily reference data, not live restock data.',
  },
  {
    id: 'retailers',
    name: 'Retailer Watch',
    mode: 'Disabled',
    health: 'Credentials required',
    lastScan: 'Never',
    nextScan: 'After an authorized adapter is configured',
    records: 0,
    access: 'Allowlisted adapters only',
    note: 'No generic scraping fallback is enabled.',
  },
];

export const portfolio = {
  cashInvested: 2148.4,
  displayedMarketValue: 2884.0,
  patientSaleValue: 2607.5,
  conservativeLiquidationValue: 2319.8,
  realisedProfit: 412.6,
  unrealisedResult: 171.4,
  deadInventory: 284.0,
  averageHoldingDays: 63,
};

export const shadowTrades = [
  {
    id: 's1',
    dealId: deals[0].id,
    name: deals[0].canonicalProduct,
    detected: '28 Aug',
    economics: deals[0].economics,
    laterSupportedNetExit: deals[0].economics.conservativeNetExit - 0.4,
    status: 'Executable',
    followUp: '7-day complete',
    dataMode: 'demo' as const,
  },
  {
    id: 's2',
    dealId: deals[2].id,
    name: deals[2].canonicalProduct,
    detected: '19 Aug',
    economics: deals[2].economics,
    laterSupportedNetExit: deals[2].economics.conservativeNetExit - 8,
    status: 'Rejected after fees',
    followUp: '30-day due',
    dataMode: 'demo' as const,
  },
  {
    id: 's3',
    dealId: deals[4].id,
    name: deals[4].canonicalProduct,
    detected: '02 Aug',
    economics: deals[4].economics,
    laterSupportedNetExit: deals[4].economics.conservativeNetExit + 4,
    status: 'Price drift',
    followUp: '30-day complete',
    dataMode: 'demo' as const,
  },
];

export const reviewItems = [
  {
    id: 'r1',
    type: 'Quantity conflict',
    title: 'Riftbound display / case ambiguity',
    source: 'eBay',
    confidence: 61,
    age: '12 min',
    severity: 'High',
    originalTitle: 'Riftbound Origins display sealed case? 24 packs',
    imageUrl: null,
    currentCandidate: 'Riftbound Origins Booster Display',
    alternativeCandidates: [
      'Riftbound Origins Booster Case',
      'Riftbound Origins loose packs',
    ],
    quantity: 1,
    language: 'English',
    condition: 'Factory sealed',
    productType: 'Display',
    riskFlags: ['Quantity ambiguity', 'Case/display terminology'],
  },
  {
    id: 'r2',
    type: 'Parser change',
    title: 'Retailer shipping price moved',
    source: 'Retailer Watch',
    confidence: 42,
    age: '18 min',
    severity: 'High',
    originalTitle: 'Retailer listing: shipping included',
    imageUrl: null,
    currentCandidate: 'Riftbound Origins Booster Display',
    alternativeCandidates: [],
    quantity: 1,
    language: 'English',
    condition: 'New',
    productType: 'Display',
    riskFlags: ['Parser field moved', 'Shipping may be omitted'],
  },
  {
    id: 'r3',
    type: 'Product match',
    title: '“Pikachu old holo 4/102” language unknown',
    source: 'Marktplaats',
    confidence: 58,
    age: '1 h',
    severity: 'Medium',
    originalTitle: 'Pikachu old holo 4/102 taal onbekend',
    imageUrl: null,
    currentCandidate: 'Pikachu 4/102 Base Set',
    alternativeCandidates: ['Pikachu Base Set 2', 'Pikachu Celebrations'],
    quantity: 1,
    language: 'Unknown',
    condition: 'Unknown from photo',
    productType: 'Single card',
    riskFlags: ['Language unknown', 'Condition unknown'],
  },
  {
    id: 'r4',
    type: 'Suspicious price',
    title: 'Sealed 151 display for €22',
    source: 'Marktplaats',
    confidence: 98,
    age: '18 min',
    severity: 'Critical',
    originalTitle: 'Pokemon 151 display box ONLY leeg / empty — read!',
    imageUrl: null,
    currentCandidate: 'Scarlet & Violet—151 Booster Bundle display',
    alternativeCandidates: ['Empty retail display packaging'],
    quantity: 1,
    language: 'Dutch',
    condition: 'Used',
    productType: 'Empty packaging',
    riskFlags: ['Empty packaging', 'Misleading headline price'],
  },
];
